In [2]:
from dotenv import load_dotenv
from azure.core.credentials import AzureKeyCredential
from azure.search.documents import SearchClient
import os
import pandas as pd
import json

from qna_extractor import qna_extractor

2025-10-21 11:17:43 - gpd_ai_companion_qna_batch - INFO - Debug mode is disabled
2025-10-21 11:17:43 - gpd_ai_companion_qna_batch - INFO - Logger configured. Log files will be saved in: /Users/ananda_ganesan@uhc.com/Library/CloudStorage/OneDrive-UHG/Documents/GAK/gpd-ai-companion-transcripts-qna/logs
2025-10-21 11:17:43 - gpd_ai_companion_qna_batch - INFO - All required environment variables loaded successfully.

In [5]:
load_dotenv()

True

In [4]:
# Maximize display width for dataframes
pd.set_option('display.max_colwidth', None)  # Show full text in cells
pd.set_option('display.width', None)         # Use maximum display width
#pd.set_option('display.max_rows', None)      # Show all rows
#pd.set_option('display.max_columns', None)   # Show all columns

In [7]:
mira_search_client = SearchClient(os.getenv("AZURE_SEARCH_SERVICE_ENDPOINT_EASTUS"),"transcripts-mira",AzureKeyCredential(os.getenv("AZURE_SEARCH_API_KEY_EASTUS")))
qna_search_client = SearchClient(os.getenv("AZURE_SEARCH_SERVICE_ENDPOINT_EASTUS"),"transcripts-ucid-qna-v5",AzureKeyCredential(os.getenv("AZURE_SEARCH_API_KEY_EASTUS")))

Get All Negative questions and extract sentiment for conversation.

In [8]:
index_name = "transcripts-ucid-qna-v5"
select_fields = ["Ucid","sentiment_level_1"]
filter = f"StartTime ge 2025-10-20T00:00:00Z and StartTime lt 2025-10-21T00:00:00Z and sentiment_level_1 eq 'Negative'"
results = qna_search_client.search(select=select_fields,filter=filter)
df = pd.DataFrame(results, columns=select_fields)  
df.shape

(9580, 2)

In [9]:
counts = df.groupby('Ucid').size()
filtered_counts = counts[counts > 1].sort_values(ascending=False)
filtered_counts.shape

(1818,)

In [11]:
filtered_counts.head(10)

Ucid
31015008480562574882    7
00102074481760989425    6
00066553761761002716    6
00066414931760970090    6
00070391761760993042    6
00067276011760988462    6
00102128301760976397    6
00070541471761004269    6
00070339991760972868    6
34611392812181641856    6
dtype: int64

In [16]:
Ucids = ",".join(filtered_counts.index[:100])
print(Ucids)

31015008480562574882,00102074481760989425,00066553761761002716,00066414931760970090,00070391761760993042,00067276011760988462,00102128301760976397,00070541471761004269,00070339991760972868,34611392812181641856,00100336611760971001,00100394691761003182,00098005941760980330,00068576031760964165,00066077881760965165,00068316901760970699,00098605061760976599,00067172191761002698,05776341692457408084,00100595691760997184,00068063261760990998,00068110561760970510,00327139211762037859,00100167921760991164,00068108891760966106,00066525891760970280,00100429731760966784,00067201001760972797,29032341982474972805,00098058561760985132,00067426211760962396,39015228730864551219,00066012181760970228,25655247232485467431,00067376851760968212,00068534001761001110,00067391111760995799,00066038171760983653,00098064391760996775,00070236141760996978,00099535841760971519,00098087821760970508,00068461191760988203,00068244391760974875,00067512421760973920,00068282841760968613,00098233151760993438,00068193051760977040,00068266881760990701,00068295761760971589,00068300661760966081,04451052360694654005,00100648881760987361,00098461121760984880,00066584601760990808,00098220121760974664,00070564791760991168,00066508171760981312,00100606731760974187,00098559851760993763,00098557701760974984,00068486291760970251,00068471391760977384,00098545051760983380,16392001210809978249,00068461011760986607,00099209961760975562,00098522881760976378,00099212791760995748,00066432771760998418,00068370241760965350,00068368141761001237,00100598431760982531,10133253651098463264,00068266701760975948,00102089701761003351,00326217782248626259,00098035761760994073,00067653081760980331,00067161541760973802,00098039581760991789,00067641081760980946,00102470941760975256,00067611761760981321,00098064981760980914,00067542281760977951,00098076121761001894,00099573841760976288,00067279931760973069,00067464691760968356,00067399891760979732,00067314761760979687,00067330411760984801,00098140601760972781,00067366591760969041,00102520871760999890,00102123531760988667,00066595191760976566,00102118881760974111,00100003471760977309

In [17]:
filter =f"search.in(Ucid,'{Ucids}',',')"
select=["Ucid","Text","StartTime"]
results = mira_search_client.search(select=select, filter=filter)
df = pd.DataFrame(results)  
df.shape

(100, 7)

Get Positive Reports from qna_v5 index report.

In [5]:
filter="sentiment_level_1 eq 'Positive'" 
select=["Ucid","question","sentiment_level_1","sentiment_level_2","StartTime"]
qna_search_client = SearchClient(os.getenv("AZURE_SEARCH_SERVICE_ENDPOINT_EASTUS"),"transcripts-ucid-qna-v5",AzureKeyCredential(os.getenv("AZURE_SEARCH_API_KEY_EASTUS")))
positive_qna = qna_search_client.search(select=select, filter=filter)
df = pd.DataFrame(positive_qna)  
df.shape

(257, 9)

In [6]:
df[select].head(10)

,Ucid,question,sentiment_level_1,sentiment_level_2,StartTime
0,12662215750637887574,Was there anything I could do to help you out here?,Positive,Grateful,2025-10-03T15:35:04.772Z
1,00066509581760460594,Are you able to help me explore the new plan that is beneficial to me?,Positive,Satisfied,2025-10-14T17:17:45.293Z
2,00099232791760542993,I would like for you to go with me with the new Medicare plan that y all have.,Positive,Satisfied,2025-10-15T15:47:58.297Z
3,00067205741760466963,Can I complete the survey to give the agent a good rating?,Positive,Grateful,2025-10-14T18:40:54.389Z
4,05910133321161914422,How does the new plan with better benefits sound?,Positive,Other,2025-10-15T19:32:58.681Z
5,00100118761759964463,What benefits did you like most about your plan? I didn’t have copayments for one.,Positive,Satisfied,2025-10-08T23:03:33.813Z
6,25894133530896537232,I got a letter saying that I would get everything and I m real happy with United Healthcare.,Positive,Satisfied,2025-10-09T18:50:22.038Z
7,00100306231759948627,I was talking to a gentleman about a problem I was having with EU card and I would like to do a survey on him because he was excellent. How can I do that?,Positive,Grateful,2025-10-08T18:40:48.77Z
8,00098518961760037633,"I have till [date] to decide which plan I m on, but I m extremely happy with your plan so if I don t say anything does it stay the same or do I have to tell you right now what I m?",Positive,Satisfied,2025-10-09T19:23:00.846Z
9,00099243951760130404,What are the key benefits of the 07 plan that I like?,Positive,Satisfied,2025-10-10T21:08:42.767Z

In [33]:
df[select].to_csv('positive_qna_v5_140.csv', index=False)

In [7]:
Ucids = ",".join(df['Ucid'])
print(Ucids)

12662215750637887574,00066509581760460594,00099232791760542993,00067205741760466963,05910133321161914422,00100118761759964463,25894133530896537232,00100306231759948627,00098518961760037633,00099243951760130404,00066202471760649804,00066416811759754707,00098280311759756927,00067182261760574460,00102632331760710299,00100078271759340467,00070538701759334415,00100117501759337627,01296100330573048640,00068169001713988969,00098394221759778591,00102635421759847202,00099144371760027406,00066536171760122701,00099605481760102725,00099398111759764236,00102548001760567042,00070193041760034218,00102320291760027125,00067141221760647025,00098617611759861017,17256011731199850885,00098191651759844978,13460095430563701000,00098152661760535660,00098628971760626516,00068640801760013649,00144355541759277442,00100154351759420561,00068267801759414424,00068565281759426172,00066070911759451136,00099069851760546047,00066027331760544394,16691392010018309205,00102424721760392256,00100120781760301028,00066065601759779616,30806375211939412784,00068484491759987388,00067477111760127335,00099440411759782625,00067510961760621601,00070001291759945872,00068484491759987388,00100563121760023904,00100004801760648716,00144275161760644586,05379223041986167569,00098116111760017442,00068304561759765537,33848083370893686854,00100571981760546205,00067130721760113197,00100322401760631443,00099502461760531124,00098178381760623642,00098556121759345337,00068250721759436693,00099189841760378131,00100120781760301028,00066425671760378747,00070271101760056453,00099635431759864537,25894133530896537232,00098650891760114252,00098171981759843149,17687374402288223252,00098338271760642430,00067204451759779973,00070374911759343676,00098591681759350340,00098157411759449175,00100499631759504239,00068374731760543700,00066405601760550843,00068056221760379958,00070457621760562939,00259263860086442121,20869386770305551426,00066376351759938180,00099287691759947762,00099201461760102193,00068517281760624638,14456060352172155735,00098631661760107097,00070001291759945872,00098116111760017442,00067304431759782195,02437209981361412913,34710129161985120326,34929177821702232211,00099242411759942223,00099164841760709547,00067127701759332164,00098645601759362684,00100141711759347632,00099540931759427325,17729187361146511895,00068367511760488154,00068538241759526560,00068649541760461741,00066054561760367986,00099507751760567351,00066090941760123873,00100203021760541373,00102447081760630166,00067412991759962539,00099542921760126454,00102592401760643864,00070395391760616753,00100304801760054136,08209259710674775127,00100326141759328747,29985133521342248048,00099421561759431464,25921307592222167895,00070510921760535070,00098636801760469623,00066426051760545897,00067147731760545458,00067497911760551759,00066620291760397630,00100471821759764678,00066292511760032483,00068484491759987388,00118084830926323750,00102387801759957587,00070058821759955234,17254384801446196787,00102047481760489695,00068352281760534686,00067439771760471452,00098068571760546141,00099335561760561514,00070396451760379981,00098067551760371970,00067134281760368223,00102439591759871857,00099144371760027406,00099465361759867312,00070453441760035778,00102352421759860725,00099461271760533756,00100150751760627584,00066634941760023689,00100415731760634180,00066174681760644078,00067515291760651322,25492335881751292261,00102372091760029680,00068494111760639067,00099200391760705650,08232229191616016000,00099154471760470562,00070605601759416653,00070401221760535664,21351338412249417286,33177146091895855478,00099163751760385168,00098357821759959655,33092251211983185494,00100306231759948627,00098152031760553965,00098358171759939233,00068468311759858625,00066111481759878926,00102191941760126557,00099570951760120660,00070453441760035778,00066428991760046099,00102466881759941756,20499094780289831203,22803016072038839300,00098084221760707703,00100519751759321324,00067112401759421648,00067512751759448214,00098015441759408422,33078307420429466517,18808290000579084342,00100618511759510857,00098574211759523090,00067199831760542048,00098433891760461384,00100081141760549264,00070326531760550462,00067282761760296588,00070335731760037260,08833141531234585168,00098476591759786747,00068141681760043916,00098021961760568380,00067469671759878355,00067445461760634033,33681349682269594489,00100167691759956558,00100264351759779467,00067019081760710930,00099200391760705650,00098116331760706756,00066053711760717044,00098180441759327153,26693297212220909665,00102268841760457732,30227328391737763201,00099145611760465215,00070593841760554956,00068080491759944924,00067438571759767491,00100512571759856449,00066067301759780812,00067130721760113197,00070001291759945872,12626290091618495313,05655123540107554088,00100641021759865270,00067469511759845445,08833386650539321459,00102325341759960558,00068010411760707993,00098265911759336623,00102417661759352915,00067604641760469728,12673131542441623686,05509374621969703249,00068501761760487511,34307003750841519120,00100640761760558846,00100226181760382623,38242179431770520709,00070270441759767642,09555213952153195558,00102127731759751284,00066533411760032724,28933052031498772481,00100014201760552239,00114590951760620224,00098584951759945209,33141133632219022150,00066536171760122701,00099022651760642564,00070157391760633638,00068076261760103017,17236379881493717360,00068484491759987388,00098346011760622043

In [10]:
print(filter)

search.in(Ucid,12662215750637887574,00066509581760460594,00099232791760542993,00067205741760466963,05910133321161914422,00100118761759964463,25894133530896537232,00100306231759948627,00098518961760037633,00099243951760130404,00066202471760649804,00066416811759754707,00098280311759756927,00067182261760574460,00102632331760710299,00100078271759340467,00070538701759334415,00100117501759337627,01296100330573048640,00068169001713988969,00098394221759778591,00102635421759847202,00099144371760027406,00066536171760122701,00099605481760102725,00099398111759764236,00102548001760567042,00070193041760034218,00102320291760027125,00067141221760647025,00098617611759861017,17256011731199850885,00098191651759844978,13460095430563701000,00098152661760535660,00098628971760626516,00068640801760013649,00144355541759277442,00100154351759420561,00068267801759414424,00068565281759426172,00066070911759451136,00099069851760546047,00066027331760544394,16691392010018309205,00102424721760392256,00100120781760301028,00066065601759779616,30806375211939412784,00068484491759987388,00067477111760127335,00099440411759782625,00067510961760621601,00070001291759945872,00068484491759987388,00100563121760023904,00100004801760648716,00144275161760644586,05379223041986167569,00098116111760017442,00068304561759765537,33848083370893686854,00100571981760546205,00067130721760113197,00100322401760631443,00099502461760531124,00098178381760623642,00098556121759345337,00068250721759436693,00099189841760378131,00100120781760301028,00066425671760378747,00070271101760056453,00099635431759864537,25894133530896537232,00098650891760114252,00098171981759843149,17687374402288223252,00098338271760642430,00067204451759779973,00070374911759343676,00098591681759350340,00098157411759449175,00100499631759504239,00068374731760543700,00066405601760550843,00068056221760379958,00070457621760562939,00259263860086442121,20869386770305551426,00066376351759938180,00099287691759947762,00099201461760102193,00068517281760624638,14456060352172155735,00098631661760107097,00070001291759945872,00098116111760017442,00067304431759782195,02437209981361412913,34710129161985120326,34929177821702232211,00099242411759942223,00099164841760709547,00067127701759332164,00098645601759362684,00100141711759347632,00099540931759427325,17729187361146511895,00068367511760488154,00068538241759526560,00068649541760461741,00066054561760367986,00099507751760567351,00066090941760123873,00100203021760541373,00102447081760630166,00067412991759962539,00099542921760126454,00102592401760643864,00070395391760616753,00100304801760054136,08209259710674775127,00100326141759328747,29985133521342248048,00099421561759431464,25921307592222167895,00070510921760535070,00098636801760469623,00066426051760545897,00067147731760545458,00067497911760551759,00066620291760397630,00100471821759764678,00066292511760032483,00068484491759987388,00118084830926323750,00102387801759957587,00070058821759955234,17254384801446196787,00102047481760489695,00068352281760534686,00067439771760471452,00098068571760546141,00099335561760561514,00070396451760379981,00098067551760371970,00067134281760368223,00102439591759871857,00099144371760027406,00099465361759867312,00070453441760035778,00102352421759860725,00099461271760533756,00100150751760627584,00066634941760023689,00100415731760634180,00066174681760644078,00067515291760651322,25492335881751292261,00102372091760029680,00068494111760639067,00099200391760705650,08232229191616016000,00099154471760470562,00070605601759416653,00070401221760535664,21351338412249417286,33177146091895855478,00099163751760385168,00098357821759959655,33092251211983185494,00100306231759948627,00098152031760553965,00098358171759939233,00068468311759858625,00066111481759878926,00102191941760126557,00099570951760120660,00070453441760035778,00066428991760046099,00102466881759941756,20499094780289831203,22803016072038839300,00098084221760707703,00100519751759321324,00067112401759421648,00067512751759448214,00098015441759408422,33078307420429466517,18808290000579084342,00100618511759510857,00098574211759523090,00067199831760542048,00098433891760461384,00100081141760549264,00070326531760550462,00067282761760296588,00070335731760037260,08833141531234585168,00098476591759786747,00068141681760043916,00098021961760568380,00067469671759878355,00067445461760634033,33681349682269594489,00100167691759956558,00100264351759779467,00067019081760710930,00099200391760705650,00098116331760706756,00066053711760717044,00098180441759327153,26693297212220909665,00102268841760457732,30227328391737763201,00099145611760465215,00070593841760554956,00068080491759944924,00067438571759767491,00100512571759856449,00066067301759780812,00067130721760113197,00070001291759945872,12626290091618495313,05655123540107554088,00100641021759865270,00067469511759845445,08833386650539321459,00102325341759960558,00068010411760707993,00098265911759336623,00102417661759352915,00067604641760469728,12673131542441623686,05509374621969703249,00068501761760487511,34307003750841519120,00100640761760558846,00100226181760382623,38242179431770520709,00070270441759767642,09555213952153195558,00102127731759751284,00066533411760032724,28933052031498772481,00100014201760552239,00114590951760620224,00098584951759945209,33141133632219022150,00066536171760122701,00099022651760642564,00070157391760633638,00068076261760103017,17236379881493717360,00068484491759987388,00098346011760622043,',')

In [11]:
#filter="StartTime gt 2025-10-15T17:49:50Z and StartTime lt 2025-10-15T17:50:00Z" #10 Records
#filter="StartTime gt 2025-10-15T17:47:00Z and StartTime lt 2025-10-15T17:50:00Z" # 137 Records
filter =f"search.in(Ucid,'{Ucids}',',')"
select=["Ucid","Text","StartTime"]
results = mira_search_client.search(select=select, filter=filter)
df = pd.DataFrame(results)  
df.shape

(243, 7)

In [18]:
df[['Ucid','Text','StartTime']].head(10)

,Ucid,Text,StartTime
0,00067376851760968212,Agent: Thank you for calling. My name is Donal...,2025-10-20T13:52:38.633Z
1,00326217782248626259,customer: If you record your name and reason f...,2025-10-20T17:43:18.675Z
2,00100606731760974187,"Agent: Hi, thank you so much for calling Unite...",2025-10-20T15:31:53.927Z
3,00067161541760973802,Agent: Thank you for calling. My name is Keely...,2025-10-20T15:25:08.976Z
4,00067464691760968356,"Agent: Hello, I do apologize for that. Thank y...",2025-10-20T14:02:24.464Z
5,00098058561760985132,Agent: Thank you for calling. This is Amanda B...,2025-10-20T18:37:43.192Z
6,00099573841760976288,Agent: Thank you for calling. How may I help y...,2025-10-20T16:13:47.726Z
7,00100648881760987361,Agent: Thank you for calling. My name is Zach....,2025-10-20T19:13:31.265Z
8,00066414931760970090,Agent: Good morning. Thank you for calling. My...,2025-10-20T14:46:21.142Z
9,00067542281760977951,Agent: Thank you for calling. My name is Kevin...,2025-10-20T16:36:41.024Z

In [19]:
def extract_sentiments(row):
    extractor = qna_extractor(question=row['Text'], project="MIRA")
    try:

        sentiment_level_1_json = extractor.extract_sentiment_level_one()
        cleaned_sentiment_1 = sentiment_level_1_json.strip()
        cleaned_sentiment_1 = cleaned_sentiment_1.replace("```json", "").replace("```", "").strip()
        cleaned_sentiment_1 = cleaned_sentiment_1.lstrip('\n').rstrip('\n')
        sentiment_level_1_data = json.loads(cleaned_sentiment_1)
        sentiment_level_1_value = sentiment_level_1_data.get('sentiment_level_1')
        #expanded_qna_1["sentiment_level_1"] = sentiment_level_1_value
        row['sentiment_level_1'] = sentiment_level_1_value 
    except Exception as e:
            print(f"Error processing Ucid {row['Ucid']}: {e}")
            row['sentiment_level_1'] = None
            row['sentiment_level_2'] = None
            return row
    try:
        sentiment_level_2_json = extractor.extract_sentiment_level_two(sentiment_level_1_value)
        # Clean the response before parsing
        cleaned_sentiment_2 = sentiment_level_2_json.strip()
        cleaned_sentiment_2 = cleaned_sentiment_2.replace("```json", "").replace("```", "").strip()
        cleaned_sentiment_2 = cleaned_sentiment_2.lstrip('\n').rstrip('\n')
        
        sentiment_level_2_data = json.loads(cleaned_sentiment_2)
        #expanded_qna_1["sentiment_level_2"] = sentiment_level_2_data.get('sentiment_level_2')
        row['sentiment_level_2'] = sentiment_level_2_data.get('sentiment_level_2')
        return row 
    except Exception as e:
            print(f"Error processing Ucid {row['Ucid']}: {e}")
            row['sentiment_level_2'] = None
            return row

df = df.apply(extract_sentiments, axis=1)
df.shape

2025-10-21 11:27:43 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:27:44 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:27:45 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:27:46 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:27:47 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:27:48 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:27:49 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:27:49 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:27:51 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:27:51 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:27:53 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:27:54 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:27:54 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:27:55 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:27:56 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:27:57 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:27:57 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:27:58 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:27:59 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:00 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:01 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:01 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:02 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:03 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:05 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:05 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:06 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:07 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:08 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:09 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:10 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:11 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:12 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:13 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:14 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:15 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:16 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:17 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:18 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:19 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:19 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:20 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:21 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:22 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:23 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:24 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:25 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:26 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:26 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:27 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:28 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:29 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:30 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:30 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:31 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:32 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:33 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:34 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:35 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:36 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:37 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:37 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:38 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:39 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:40 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:41 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:42 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:43 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:44 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:45 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:46 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:47 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:48 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:48 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:50 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:51 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:51 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:52 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:53 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:54 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:55 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:56 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:57 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:28:58 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:28:59 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:00 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:01 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:02 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:03 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:04 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:05 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:06 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:07 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:08 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:09 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:09 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:10 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:11 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:12 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:13 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:15 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:15 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:16 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:17 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:18 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:19 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:20 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:21 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:22 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:23 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:23 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:24 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:25 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:26 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:27 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:28 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:29 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:30 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:31 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:32 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:33 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:34 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:35 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:36 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:37 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:38 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:39 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:40 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:41 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:42 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:43 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:44 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:45 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:46 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:46 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:47 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:48 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:49 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:50 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:51 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:52 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:53 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:54 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:55 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:56 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:57 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:57 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:29:58 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:29:59 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:30:01 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:30:02 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:30:03 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:30:04 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:30:05 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:30:06 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:30:07 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:30:08 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:30:09 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:30:10 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:30:10 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:30:11 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.
2025-10-21 11:30:12 - gpd_ai_companion_qna_batch - INFO - sentiment_level_2_extraction extraction completed successfully.
2025-10-21 11:30:13 - gpd_ai_companion_qna_batch - INFO - sentiment_level_1_extraction extraction completed successfully.

(100, 9)

In [20]:
df.groupby('sentiment_level_1').size()

sentiment_level_1
Negative    91
Neutral      9
dtype: int64

In [21]:
df[['Ucid','Text','StartTime','sentiment_level_1','sentiment_level_2']].head(10)

,Ucid,Text,StartTime,sentiment_level_1,sentiment_level_2
0,00067376851760968212,Agent: Thank you for calling. My name is Donal...,2025-10-20T13:52:38.633Z,Negative,Frustrated
1,00326217782248626259,customer: If you record your name and reason f...,2025-10-20T17:43:18.675Z,Negative,Frustrated
2,00100606731760974187,"Agent: Hi, thank you so much for calling Unite...",2025-10-20T15:31:53.927Z,Neutral,Procedural
3,00067161541760973802,Agent: Thank you for calling. My name is Keely...,2025-10-20T15:25:08.976Z,Neutral,Procedural
4,00067464691760968356,"Agent: Hello, I do apologize for that. Thank y...",2025-10-20T14:02:24.464Z,Negative,Frustrated
5,00098058561760985132,Agent: Thank you for calling. This is Amanda B...,2025-10-20T18:37:43.192Z,Negative,Frustrated
6,00099573841760976288,Agent: Thank you for calling. How may I help y...,2025-10-20T16:13:47.726Z,Negative,Frustrated
7,00100648881760987361,Agent: Thank you for calling. My name is Zach....,2025-10-20T19:13:31.265Z,Neutral,Informational
8,00066414931760970090,Agent: Good morning. Thank you for calling. My...,2025-10-20T14:46:21.142Z,Negative,Frustrated
9,00067542281760977951,Agent: Thank you for calling. My name is Kevin...,2025-10-20T16:36:41.024Z,Negative,Frustrated

In [19]:
df.groupby('sentiment_level_1').size()

sentiment_level_1
Negative     42
Neutral     165
Positive     34
dtype: int64

In [29]:
df[df['sentiment_level_1']=='Positive']['Text']

10    Agent: Good *********. My name is Joshua. How can I help you *****? customer: Oh my God, I'm so happy you speak English. customer: I can't even. Agent: I'm glad, I'm glad that you can find out there. I, I, I don't speak like 100%, but I can understand it and, and speak it. OK. customer: You can't believe the phone calls I at. customer: Where I can? Agent: You've been through a lot of in Spanish or other languages. customer: Oh my God, I you know, but I apologize for being so forward. But thank you. Agent: No, no worries, we're here to help. OK, OK, so how can I help you *****? customer: I wanted to. customer: Well, I have a policy with United Healthcare. Agent: Mm-hmm. Agent: Yes. customer: And I think I have to renew it, don't I? It's a renewal period coming up. Agent: So yes, we can check on that. If you can renew the same plan that you're having for ********* for t************ or if there is a better plan and I can see that it benefits you more, I could let you know the new plan and you can go into that plan too. customer: OK. customer: Alright you you need my member ID. Agent: OK, so before we do this. Agent: Yes, but let's confirm HIPAA really quick. So what is your name? customer: Uh, Deb, Debbie M Chapman. Agent: Perfect. OK. And what is your birthday? customer: 11848. Agent: OK. And what is your phone number? customer: ************. Agent: Perfect, and your full address. customer: 100 Knepper KNEPPER Street. Agent: Perfect. Thank you so much for that. Agent: Just a coupl************ until the system finds it quicker profile. Agent: OK. Agent: No, let's go back and open your profile. It's right here. Agent: OK. It said that you're counting it's Mills.
73                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Agent: Yes. customer: Thank you for calling the auto.
Name: Text, dtype: object

In [22]:
df[['Ucid','Text','sentiment_level_1','sentiment_level_2']].to_csv('conversation_sentiments_100_Negatives.csv', index=False)

In [16]:

extractor = qna_extractor(project="MIRA")
df['sentiment_level_1'] = df.apply(lambda row: extractor.extract_sentiment_level_one(row['Text']), axis=1)
#df['sentiment_level_2'] = df.apply(lambda row: extractor.extract_sentiment_level_two(row['sentiment_level_1'], row['Text']), axis=1)
df.shape

TypeError: qna_extractor.extract_sentiment_level_one() takes 1 positional argument but 2 were given